name: MitoHiFi Integration Test

# on: workflow_dispatch
on:
  push:
    branches:
    - 'reviews'

jobs:
  integration_test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: ghcr.io/marcelauliano/mitohifi:reviews

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      - name: Run integration test with Docker
        run: |
          docker run mitohifi:reviews python3 mitohifi.py --help