name: MitoHiFi Integration Test

# on: workflow_dispatch
on:
  push:
    branches:
    - 'reviews'

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      - name: Run integration test_contigs with Docker
        run: |
          docker pull ghcr.io/marcelauliano/mitohifi:reviews
          docker run ghcr.io/marcelauliano/mitohifi:reviews \
            mitohifi.py \
            -c /opt/MitoHiFi/tests/ilPhaBuce1_contig.fa \
            -f /opt/MitoHiFi/tests/NC_016067.1.fasta \
            -g /opt/MitoHiFi/tests/NC_016067.1.gb \
            -o 5 \
            -t 1
      
      - name: Run integration test_reads with Docker
        run: |
          docker run ghcr.io/marcelauliano/mitohifi:reviews \
            mitohifi.py \
            -r /opt/MitoHiFi/tests/ilDeiPorc1.reads.100 \
            -f /opt/MitoHiFi/tests/MW539688.1.fasta \
            -g /opt/MitoHiFi/tests/MW539688.1.gb \
            -o 5 \
            -t 1
          
          

